---
- name: Downloading the The Jenkins.war file
  get_url:
    url: https://get.jenkins.io/war-stable/2.346.2/jenkins.war
    dest: /opt/apache-tomcat-9.0.65/webapps
- name: Starting the Apache Tomcat Server Software
  shell: nohup /opt/apache-tomcat-9.0.65/bin/startup.sh

