---
- name: Download Apache Tomcat Server Package
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz 
    dest: /opt
- name: Extracting the  Apache Tomcat Server Tar File.
  unarchive:
    src: /opt/apache-tomcat-9.0.65.tar.gz
    dest: /opt
    remote_src: yes
